### ISSUE TITLE
only one proxy 

### ISSUE THREAD

**Issue by jeremiah1232** [oOHiyoriOo/PFPS#1]
only proxy show up in each file besides big proxy.txt and that 1 proxy changes every so often

**Comment by oOHiyoriOo** [comment]
ill check that out, give me a second :D 

EDIT:
could you provide aditional information please? like what os, Linux? Windows? Unix?
which file? (iam sure you mean the getProxy.py (Slower version of both.)) but just in case i miss something, just say which it is :P

**Comment by oOHiyoriOo** [comment]
I Fixxed the issue in line 21 (latest commit).

**Comment by jeremiah1232** [comment]
I'm in os Linux and yes I mean get proxy.py

**Comment by oOHiyoriOo** [comment]
I renamed the multiHit which is the faster one to getProxy and the getProxy you used (slower one) is not getProxy_old.py
the con of the faster one is it only stores everything into one big file rn, I am working on the splittet versions as well, but consider using this one as it is the one I update more often and take more care of.
